export const listData = [
  {
    title: "A Great Apartment Next to the Beach!",
    price: 1000,
    images: ["https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "456 Park Avenue, London",
    city: "London",
    bedroom: 2,
    bathroom: 1,
    latitude: "51.5074",
    longitude: "-0.1278",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  },
  {
    title: "An Awesome Apartment Near the Park! Almost too good to be true!",
    price: 1500,
    images: ["https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "789 Oxford Street, London",
    city: "London",
    bedroom: 3,
    bathroom: 2,
    latitude: "52.4862",
    longitude: "-1.8904",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  },
  {
    title: "A New Apartment in the City!",
    price: 800,
    images: ["https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "101 Baker Street, London",
    city: "London",
    bedroom: 1,
    bathroom: 1,
    latitude: "53.4808",
    longitude: "-2.2426",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  },
  {
    title: "Great Location! Great Price! Great Apartment!",
    price: 1000,
    images: ["https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "234 Kingsway, London",
    city: "London",
    bedroom: 2,
    bathroom: 1,
    latitude: "53.8008",
    longitude: "-1.5491",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  },
  {
    title: "Apartment 5",
    price: 1500,
    images: ["https://images.pexels.com/photos/276625/pexels-photo-276625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "567 Victoria Road, London",
    city: "London",
    bedroom: 3,
    bathroom: 2,
    latitude: "53.4084",
    longitude: "-2.9916",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  },
  {
    title: "Apartment 6",
    price: 800,
    images: ["https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "890 Regent Street, London",
    city: "London",
    bedroom: 1,
    bathroom: 1,
    latitude: "54.9783",
    longitude: "-1.6174",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  },
  {
    title: "Apartment 7",
    price: 1000,
    images: ["https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "112 Piccadilly, London",
    city: "London",
    bedroom: 2,
    bathroom: 1,
    latitude: "53.3811",
    longitude: "-1.4701",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  },
  {
    title: "Apartment 8",
    price: 1500,
    images: ["https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "8765 Main High Street, London",
    city: "London",
    bedroom: 3,
    bathroom: 2,
    latitude: "51.4545",
    longitude: "-2.5879",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  },
  {
    title: "Luxury Downtown Apartment",
    price: 2000,
    images: ["https://images.pexels.com/photos/1468387/pexels-photo-1468387.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "432 Main Street, London",
    city: "London",
    bedroom: 4,
    bathroom: 3,
    latitude: "51.5007",
    longitude: "-0.1246",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  },
  {
    title: "Modern Loft Apartment",
    price: 1800,
    images: ["https://images.pexels.com/photos/1447141/pexels-photo-1447141.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    address: "789 Green Street, London",
    city: "London",
    bedroom: 3,
    bathroom: 2,
    latitude: "51.5285",
    longitude: "-0.1338",
    type: "rent",
    property: "apartment",
    createdAt: new Date(),
    userId: "1",
    postDetail: null,
    savedPosts: []
  }
];



export const singlePostData = {
  id: 1,
  title: "Beautiful Apartment",
  price: 1200,
  images: [
    "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  ],
  bedRooms: 2,
  bathroom: 1,
  size: 861,
  latitude: 51.5074,
  longitude: -0.1278,
  city: "London",
  address: "1234 Broadway St",
  school: "250m away",
  bus: "100m away",
  restaurant: "50m away",
  description:
    "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
};

export const userData = {
  id: 1,
  name: "John Doe",
  img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
};